//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntiEspais
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTITATS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTITATS()
        {
            this.EQUIPS = new HashSet<EQUIPS>();
            this.TELEFONS_ENTITATS = new HashSet<TELEFONS_ENTITATS>();
        }
    
        public int id { get; set; }
        public string temporada { get; set; }
        public string nom { get; set; }
        public string contrasenya { get; set; }
        public string adresa { get; set; }
        public string nif { get; set; }
        public string email { get; set; }
        public string ruta_imagen { get; set; }
        public string ruta_video { get; set; }
        public double altitud { get; set; }
        public double latitud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPS> EQUIPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TELEFONS_ENTITATS> TELEFONS_ENTITATS { get; set; }
    }
}
