
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntiEspais
{

using System;
    using System.Collections.Generic;
    
public partial class FAQS
{

    public int id { get; set; }

    public string pregunta { get; set; }

    public string descripción { get; set; }

}

}
