//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntiEspais
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARI_INSTALACIO
    {
        public int id_dia { get; set; }
        public int id_hores { get; set; }
        public int id_instalacio { get; set; }
    
        public virtual DIA_SEMANA DIA_SEMANA { get; set; }
        public virtual HORES HORES { get; set; }
        public virtual INSTALACIONS INSTALACIONS { get; set; }
    }
}
