
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntiEspais
{

using System;
    using System.Collections.Generic;
    
public partial class HORES
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HORES()
    {

        this.DEMANDA_ACT = new HashSet<DEMANDA_ACT>();

        this.HORARI_ACTIVITAT = new HashSet<HORARI_ACTIVITAT>();

        this.HORARI_INSTALACIO = new HashSet<HORARI_INSTALACIO>();

    }


    public int id { get; set; }

    public System.TimeSpan inici { get; set; }

    public System.TimeSpan fi { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DEMANDA_ACT> DEMANDA_ACT { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HORARI_ACTIVITAT> HORARI_ACTIVITAT { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HORARI_INSTALACIO> HORARI_INSTALACIO { get; set; }

}

}
