

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntiEspais
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ENTI_ESPAISEntities : DbContext
{
    public ENTI_ESPAISEntities()
        : base("name=ENTI_ESPAISEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ACTIVITATS> ACTIVITATS { get; set; }

    public virtual DbSet<ADMINISTRADORS> ADMINISTRADORS { get; set; }

    public virtual DbSet<CATEGORIA_EDAT> CATEGORIA_EDAT { get; set; }

    public virtual DbSet<CATEGORIA_EQUIP> CATEGORIA_EQUIP { get; set; }

    public virtual DbSet<COMPETICIONS> COMPETICIONS { get; set; }

    public virtual DbSet<DEMANDA_ACT> DEMANDA_ACT { get; set; }

    public virtual DbSet<DIA_SEMANA> DIA_SEMANA { get; set; }

    public virtual DbSet<ENTITATS> ENTITATS { get; set; }

    public virtual DbSet<EQUIPS> EQUIPS { get; set; }

    public virtual DbSet<ESPAIS> ESPAIS { get; set; }

    public virtual DbSet<ESPORTS> ESPORTS { get; set; }

    public virtual DbSet<FAQS> FAQS { get; set; }

    public virtual DbSet<HORARI_ACTIVITAT> HORARI_ACTIVITAT { get; set; }

    public virtual DbSet<HORARI_INSTALACIO> HORARI_INSTALACIO { get; set; }

    public virtual DbSet<HORES> HORES { get; set; }

    public virtual DbSet<INSTALACIONS> INSTALACIONS { get; set; }

    public virtual DbSet<SEXE> SEXE { get; set; }

    public virtual DbSet<TELEFONS_INSTALACIONS> TELEFONS_INSTALACIONS { get; set; }

    public virtual DbSet<TELEFONS_ENTITATS> TELEFONS_ENTITATS { get; set; }

}

}

